chore(ci): coverage
hashicorp/dev-portal pull request #1016
Opened 2022-09-14 21:34 UTC by thiskevinwang

## 🔗 Relevant links

- [Preview link](https://dev-portal-git-BRANCH_NAME-hashicorp.vercel.app/PATH_TO_VIEW) 🔎
- [Asana task](url) 🎟️

## 🗒️ What

## 🤷 Why

## 🛠️ How

## 📸 Design Screenshots

## 🧪 Testing

## 💭 Anything else?

2022-09-19 14:02 UTC, thiskevinwang commented
It looks like as long as `undefined` is being hardcoded here in the coverage reporting action, `threshold` will always default to `60`

https://github.com/ArtiomTr/jest-coverage-report-action/blob/main/src/stages/createReport.ts#L37

2022-09-19 14:03 UTC, thiskevinwang commented on jest.config.js
> +	// https://jestjs.io/docs/configuration#coveragethreshold-object
```suggestion
	// https://jestjs.io/docs/configuration#coveragethreshold-object
	// Note: There is a bug in jest-coverage-report-action that 
	// causes this coverageThreshold to be ignored, and defaulting to 60.
	// - https://github.com/ArtiomTr/jest-coverage-report-action/blob/main/src/stages/createReport.ts#L37
```

2022-09-19 17:42 UTC, mhonnatti commented
@BRKalow it looks like @thiskevinwang 's research has landed on the 🔴 being an issue with the way the coverage reporter GH action handles thresholds and our low coverage level. I'm okay okay with this "bug" for the time being. your thoughts?

2022-09-19 17:55 UTC, thiskevinwang commented
> @BRKalow it looks like @thiskevinwang 's research has landed on the 🔴 being an issue with the way the coverage reporter GH action handles thresholds and our low coverage level. I'm okay okay with this "bug" for the time being. your thoughts?

@mhonnatti — (@BRKalow highlighted this bug last week)

2022-09-21 22:29 UTC, mhonnatti approved these changes

2022-09-21 22:38 UTC, BRKalow requested changes
Thanks for taking a stab at this! I think if we can't figure out how to not make it red every time, we should explore another action or at least wait until we're through with our crunch to ship for GA. Otherwise I think it'll just be extra noise and a distraction that's not actionable.

2023-02-13 12:05 UTC, closed without merging