[wip] update company logos collection cards
hashicorp/dev-portal pull request #1756
Opened 2023-03-16 23:51 UTC by kendallstrautman

## 🔗 Relevant links

- [Preview link](https://dev-portal-git-BRANCH_NAME-hashicorp.vercel.app/PATH_TO_VIEW) 🔎
- [Asana task](url) 🎟️

## 🗒️ What

## 🤷 Why

## 🛠️ How

## 📸 Design Screenshots

## 🧪 Testing

## 💭 Anything else?

2023-03-17 20:31 UTC, kendallstrautman commented on src/views/product-landing/components/overview-cta/overview-cta.module.css
> +	min-width: min(100%, 260px);
Oops these should be on the other PR

2023-03-20 22:04 UTC, kendallstrautman commented on src/components/collection-card/components/company-logo/index.tsx
> +function ThemedLogo({
Could add a note here as a breadcrumb. 

Eventually we will lift up a global `ThemedImage` component. Took the skateboard approach here and duplicated the approach from https://github.com/hashicorp/dev-portal/pull/1752 for this specific context.

2023-03-20 23:12 UTC, kellyschummer approved these changes
lgtm!! 🏅

2023-03-22 01:36 UTC, ashleemboyer requested changes
This PR includes more than logo changes in collection cards -- also includes changes to every product landing page. Can the two be separated for ease of reviewing? 🙏🏻

2023-03-22 18:01 UTC, ashleemboyer reviewed
Functionality is looking good, have a couple of questions for clarity! 🙋🏻

- Is there a naming convention we're using for the image files? I see a mix of using hyphens and underscores, so just want to check.
- What does `_dm` signify? Dark mode?

2023-03-22 19:07 UTC, ashleemboyer commented
> @ashleemboyer yes _dm signifies dark mode. Would you prefer that I update to use a hyphen for this suffix?

@kendallstrautman I see value in using one or the other for consistency, so since hyphens are used on the existing file names I think hyphens would be good! What are your thoughts on spelling out the `dm` abbreviation for clarity?

2023-03-22 19:30 UTC, kendallstrautman commented
Sure I can do that! 👍🏻

2023-03-22 22:36 UTC, kendallstrautman commented
@ashleemboyer I've updated the asset names! lmk if that looks good to you

2023-03-23 18:20 UTC, zchsh approved these changes
✅ I checked out the preview, looks great!

2023-03-23 20:29 UTC, kendallstrautman commented
@ashleemboyer let me know if you still have blocking feedback here 👐🏻

2023-03-23 20:57 UTC, ashleemboyer commented
> @ashleemboyer let me know if you still have blocking feedback here 👐🏻

@kendallstrautman just now getting a moment to re-review! Taking a look now 😊

2023-03-23 21:12 UTC, merged