Add docs for ProductData properties
hashicorp/dev-portal pull request #189
Opened 2022-03-16 20:24 UTC by dstaley

## "Ready for Review" checklist

- [ ] The Vercel preview link has been added to this PR's description
- [ ] The Asana task has been added to this PR's description
- [ ] This PR's link has been added to the "📐 Pull Request" field on the Asana task
- [ ] This Vercel preview link has been added to the "🔍 Preview" field on the Asana task
- [ ] The description template has been filled in below

---

## Relevant links

- [Preview link](https://dev-portal-git-BRANCH_NAME-hashicorp.vercel.app/PATH_TO_VIEW) 🔎
- [Asana task](url) 🎟️

## What

This PR adds JSDoc comments for all the properties used in `src/data/<product>.json` files, and updates the README within that folder to reference the types.

## Why

## How

## Testing

## Anything else?

2022-03-16 20:30 UTC, dstaley commented
@ashleemboyer Feel free to ignore my guesses at the DevDot-specific properties 😅 Happy to update those to match what you come up with.

2022-03-16 21:43 UTC, ashleemboyer requested changes

2022-03-16 21:43 UTC, ashleemboyer commented on src/data/types.d.ts
> +  navigationHeaderItems: NavigationHeaderItem[]
These are defined in another file and documenting them is part of another task I'm working on. They can be removed!

2022-03-16 21:43 UTC, ashleemboyer commented on src/data/types.d.ts
> +  id: string
Same as previous comment, this is already defined elsewhere and I'll handle documenting it in my other task. 😊

2022-03-16 21:43 UTC, ashleemboyer commented on src/data/types.d.ts
> +}
Same as previous. 😊

2022-03-17 13:16 UTC, ashleemboyer approved these changes
🥳

2022-03-17 21:53 UTC, merged