[WIP] feat: adds interactive lab embed
hashicorp/dev-portal pull request #206
Opened 2022-03-18 22:52 UTC by kendallstrautman

## "Ready for Review" checklist

- [ ] The Vercel preview link has been added to this PR's description
- [ ] The Asana task has been added to this PR's description
- [ ] This PR's link has been added to the "📐 Pull Request" field on the Asana task
- [ ] This Vercel preview link has been added to the "🔍 Preview" field on the Asana task
- [ ] The description template has been filled in below

---

## Relevant links

- [Preview link](https://dev-portal-git-BRANCH_NAME-hashicorp.vercel.app/PATH_TO_VIEW) 🔎
- [Asana task](url) 🎟️

## What

## Why

## How

## Testing

## Anything else?

2022-03-21 16:01 UTC, kendallstrautman commented on src/components/lab-embed/embed-element/index.tsx
> +  provider: HandsOnLabProviderOption
Should be instruqt only

2022-03-21 17:50 UTC, kendallstrautman commented on src/components/lab-embed/embed-element/index.tsx
> +import { MutableRefObject, useRef, useEffect } from 'react'
See the [lab embed in Learn](https://github.com/hashicorp/learn/tree/master/components/lab-embed), copied from there.

2022-03-21 17:51 UTC, kendallstrautman commented on src/components/lab-embed/resizable/components/img/resize_bar.svg
> +<svg width="120" height="14" fill="none" xmlns="http://www.w3.org/2000/svg"><rect width="120" height="4" rx="2" fill="var(--gray-5, #dbdbdc)"/><rect y="10" width="120" height="4" rx="2" fill="var(--g
<img width="1743" alt="Screen Shot 2022-03-18 at 4 07 57 PM" src="https://user-images.githubusercontent.com/36613477/159333959-53ad3c1e-7282-44bf-bb03-4cbe12b9431e.png">

2022-03-21 17:52 UTC, kendallstrautman commented on src/components/lab-embed/resizable/components/resizer.module.css
> +  background: var(--token-color-palette-neutral-50);
I updated these colors to use design token values. Just sort of eye-balled it.

2022-03-22 18:16 UTC, kendallstrautman commented
I just rebased this back onto main to get the vault routes and now the deploy is failing because of a packer docs thing. Looking into it.

2022-03-22 21:04 UTC, ashleemboyer requested changes
This is a really great start! ✨ Love learning about how this interactive frame works. Have a couple of areas of feedback and a couple of comments just thinking out loud.

2022-03-22 21:04 UTC, ashleemboyer commented on src/views/tutorial-view/index.tsx
> +          <InteractiveLabToggle showButton={Boolean(handsOnLab?.id)} />
Thoughts on removing the `showButton` prop and conditionally rendering this component instead?

```tsx
{isInteractive && <InteractiveLabToggle />}
```

Also seeing that the `isInteractive` logic is defined in two different ways, we probably want just one:

- `Boolean(handsOnLab)` (in the `tutorialMeta` object just above this)
- `Boolean(handsOnLab?.id)`

2022-03-22 21:04 UTC, ashleemboyer commented on src/views/tutorial-view/index.tsx
> +  const InteractiveLabWrapper = handsOnLab?.id ? InstruqtProvider : Fragment
Relevant to previous comment, I think you could define a `isInteractive` boolean variable above this and use it on this line and down below in the markup where my other comment is.

2022-03-22 21:23 UTC, kendallstrautman commented on src/components/lab-embed/resizable/components/img/resize_bar.svg
> +<svg width="120" height="14" fill="none" xmlns="http://www.w3.org/2000/svg"><rect width="120" height="4" rx="2" fill="var(--gray-5, #dbdbdc)"/><rect y="10" width="120" height="4" rx="2" fill="var(--g
Sounds good! I'll adjust the color

2022-03-22 21:25 UTC, kendallstrautman commented on src/components/lab-embed/resizable/components/resizer.tsx
> +}
Sure! Sounds good

2022-03-22 21:41 UTC, kendallstrautman commented on src/components/lab-embed/resizable/index.tsx
> +        panelActive={panelActive}
Cool, I'll refactor

2022-03-22 22:04 UTC, kendallstrautman commented
@ashleemboyer thank you 🙇 I think I addressed most of your feedback. lmk if you see anything else!

2022-03-23 13:44 UTC, ashleemboyer approved these changes
One last suggestion, but approving so you can merge when ready! 🥇

2022-03-23 13:44 UTC, ashleemboyer commented on src/views/tutorial-view/index.tsx
> +              isInteractive: Boolean(handsOnLab),
```suggestion
              isInteractive,
```

2022-03-23 15:31 UTC, kendallstrautman commented on src/views/tutorial-view/index.tsx
> +              isInteractive: Boolean(handsOnLab),
ty! 🙇

2022-03-23 18:23 UTC, merged