Consul Associate 003 developer page
hashicorp/dev-portal pull request #2393
Opened 2024-03-26 15:03 UTC by lszpunar

## 🔗 Relevant links

- [Preview link](https://dev-portal-git-cert-update-consul-cert-page-hashicorp.vercel.app/certifications/networking-automation) 🔎

## 🗒️ What

## 🤷 Why

## 🛠️ How

## 📸 Design Screenshots

## 🧪 Testing

## 💭 Anything else?

2024-03-27 14:20 UTC, eddie-rowe approved these changes
LGTM

Thank you for updating this!

2024-03-28 22:04 UTC, heatlikeheatwave commented on src/content/certifications/programs/networking-automation.json
> +				"prepare": "/consul/tutorials/certification-003"
Missing a closing bracket here. [The build](https://vercel.com/hashicorp/dev-portal/DRwuC5cRtBvaKWmSGqAwKGd5tQLg) should pass once this is fixed 
```suggestion
			"links": {
				"prepare": "/consul/tutorials/certification-003"
				}
```

2024-04-04 20:26 UTC, lszpunar commented on src/content/certifications/exam-faqs/consul-associate-003.mdx
> +| 9    | Monitor Consul |
```suggestion
| | (002) objectives ****NOT**** covered in (003) |
|  ---- | ------------ |
| 4    | Access the Consul key/value (KV) |

| | (002) objectives now covered within other objectives in (003) |
| ---- | --------------------- |
| 1   | Explain Consul Architecture |
| 2   | Deploy a single datacenter |
| 7   | Secure agent communication |
| 9   | Use gossip encryption |

| | ****NEW**** objectives in (003) |
| ---- | -------------- |
| 1c   | Summarize how Consul controls access to services at point of entry |
| 1d   | Discuss how Consul automates networking tasks |
| 2d   | Understand that Consul can run on multiple platforms |
| 3c   | Configure and start Consul on Kubernetes |
| 8    | Secure and connect service mesh applications at scale |
| 9    | Monitor Consul |
```

2024-04-04 20:27 UTC, lszpunar commented on src/content/certifications/exam-faqs/consul-associate-003.mdx
> +| 9    | Monitor Consul |
![image](https://github.com/hashicorp/dev-portal/assets/47227843/fa25c5c3-0505-4538-8744-11da5908224f)

2024-04-05 17:17 UTC, AshNorman requested changes
Amended requirements section

2024-04-05 17:34 UTC, AshNorman approved these changes
All good!

2024-04-05 18:14 UTC, merged