docs: waypoint download page changes
hashicorp/dev-portal pull request #262
Opened 2022-04-05 21:28 UTC by karl-cardenas-coding

## "Ready for Review" checklist

This PR updates the Waypoint download links. 

- [ ] The Vercel preview link has been added to this PR's description
- [ ] The Asana task has been added to this PR's description
- [ ] This PR's link has been added to the "📐 Pull Request" field on the Asana task
- [ ] This Vercel preview link has been added to the "🔍 Preview" field on the Asana task
- [ ] The description template has been filled in below

---

## Relevant links

- [Preview link](https://dev-portal-git-BRANCH_NAME-hashicorp.vercel.app/PATH_TO_VIEW) 🔎
- [Asana task](https://app.asana.com/0/1201979547919485/1201979547919574) 🎟️

## What

## Why

I changed the tutorials cards to focus on two themes. Getting started, and cloud providers. 
The first row focuses on the generic getting started, and the Kubernetes, and Nomad collection. I removed the Install, as it is redundant with the existing information on the page. The second row targets the cloud providers, which are more common usecases and more relevant to the practittioner. 

## How

## Testing

## Anything else?

2022-04-05 21:30 UTC, BrandonRomano commented
Brilliant!  I am not sure why the deployment failed... I will ask my team 🤔

2022-04-05 21:35 UTC, BrandonRomano approved these changes
Okey I just rebased, I believe that will fix our build error.

I defer to @tunzor for content review side of things.

2022-04-06 12:43 UTC, tunzor reviewed
Good choices on the featured tutorials!
Minor copy/paste typo but otherwise LGTM

2022-04-06 12:45 UTC, tunzor requested changes

2022-04-06 12:45 UTC, tunzor commented on src/data/waypoint-install.json
> +      "href": "https://learn.hashicorp.com/collections/waypoint/get-started-nomad"
```suggestion
      "href": "https://learn.hashicorp.com/collections/waypoint/deploy-azure"
```

2022-04-06 13:13 UTC, ashleemboyer commented on src/data/waypoint-install.json
> +      "description": "Learn how you can use Waypoin to deploy application to a Kubernetes cluster.",
```suggestion
      "description": "Learn how you can use Waypoint to deploy application to a Kubernetes cluster.",
```

2022-04-06 15:14 UTC, karl-cardenas-coding commented on src/data/waypoint-install.json
> +      "description": "Learn how you can use Waypoin to deploy application to a Kubernetes cluster.",
Nice catch @ashleemboyer :)

2022-04-06 17:59 UTC, merged