feat: fetch redirects from udr for migrated repos
hashicorp/dev-portal pull request #2658
Opened 2024-12-18 17:27 UTC by LeahMarieBush

## 🔗 Relevant links

- [Preview link](https://dev-portal-git-BRANCH_NAME-hashicorp.vercel.app/PATH_TO_VIEW) 🔎
- [Asana task](url) 🎟️

## 🗒️ What

## 🤷 Why

## 🛠️ How

## 📸 Design Screenshots

## 🧪 Testing

## 💭 Anything else?

2024-12-18 17:56 UTC, RubenSandwich commented on build-libs/redirects.js
> +		config.flags?.unified_docs_migrated_repos?.find((repo) => repo === repoName)
@LeahMarieBush can you also add a check if we are in the using the unified-docs-sandbox?

process.env.HASHI_ENV === 'unified-docs-sandbox'

2024-12-18 17:57 UTC, RubenSandwich commented on build-libs/__tests__/redirects.test.ts
> +describe('getRedirectsFromContentRepo', () => {
Surprised this function didn't have any testing yet...

2024-12-18 18:02 UTC, RubenSandwich requested changes
A small changes noted in this comment:
* https://github.com/hashicorp/dev-portal/pull/2658/files#r1890634025

Also it looks like from redirect test file [that we have to handle a few more .js to .json cases in our UDR migration script](https://github.com/hashicorp/dev-portal/blob/0152c6f97fba7782192d116a3fcd6895f76c8ede/build-libs/__tests__/redirects.test.ts#L50). Namely that we need to add quotes around the following keys:
* key
* value
* has
* type

2024-12-18 18:05 UTC, RubenSandwich commented on build-libs/redirects.js
> +		}
@LeahMarieBush If we fail to get a good response for the redirects API we should at least console.error. (If not fail the build, but I'm not sure about failing the build yet. I need to think through that case...)

2024-12-18 20:18 UTC, LeahMarieBush commented
> A small changes noted in this comment:
> 
> * https://github.com/hashicorp/dev-portal/pull/2658/files#r1890634025
> 
> Also it looks like from redirect test file [that we have to handle a few more .js to .json cases in our UDR migration script](https://github.com/hashicorp/dev-portal/blob/0152c6f97fba7782192d116a3fcd6895f76c8ede/build-libs/__tests__/redirects.test.ts#L50). Namely that we need to add quotes around the following keys:
> 
> * key
> * value
> * has
> * type

@RubenSandwich I'll get an asana task written to handle these cases in the script 👍 Thanks for pointing them out

2024-12-19 16:05 UTC, RubenSandwich approved these changes
Looks great. 👍🏻

2024-12-19 17:26 UTC, merged