[WIP] collection view: adds stubbed layout
hashicorp/dev-portal pull request #299
Opened 2022-04-12 18:16 UTC by kendallstrautman

## "Ready for Review" checklist

- [ ] The Vercel preview link has been added to this PR's description
- [ ] The Asana task has been added to this PR's description
- [ ] This PR's link has been added to the "📐 Pull Request" field on the Asana task
- [ ] This Vercel preview link has been added to the "🔍 Preview" field on the Asana task
- [ ] The description template has been filled in below

---

## Relevant links

- [Preview link](https://dev-portal-git-BRANCH_NAME-hashicorp.vercel.app/PATH_TO_VIEW) 🔎
- [Asana task](url) 🎟️

## What

## Why

## How

## Testing

## Anything else?

2022-04-13 18:32 UTC, kendallstrautman commented on src/views/tutorial-view/server.ts
> +      product: { name: product.name, filename: product.slug },
Just a rename here to make it more semantic 👍

2022-04-13 18:33 UTC, kendallstrautman commented on src/views/product-tutorials-view/helpers.ts
> +export function filterAndSortCollections(
Separated out the sorting from filtering, to be more functional for this use case.

2022-04-13 18:53 UTC, zchsh approved these changes
✅ Looks great to me:

✓ - collections sidebar in preview matches Learn currently
✓ - sidebar & breadcrumb links work
✓ - sidecar links work (in the context of this PR)

re: sidecar links, I think this is outside the scope of this PR, but I am seeing some weird behaviour - possibly related to the amount of available space & only having two headings?

![CleanShot 2022-04-13 at 14 49 31](https://user-images.githubusercontent.com/4624598/163249829-503b19ad-3751-4c15-9e8f-1d30af01d40a.gif)

Have opened [a task to investigate](https://app.asana.com/0/1202097197789424/1202125773561669/f) this cause I think it's outside the scope of this PR 👍

2022-04-13 18:53 UTC, zchsh commented on src/views/collection-view/components/collection-view-sidebar.tsx
> +export default function CollectionViewSidebar({
I for one love smaller component files, even if it means have to traverse more files 😍👍 very on board with this!

2022-04-13 18:53 UTC, zchsh commented on src/views/collection-view/index.tsx
> +      <h2 id={layoutProps.headings[1].slug}>Tutorials</h2>
oooh yeah good callout 🤔

2022-04-13 20:02 UTC, ashleemboyer requested changes
Not sure if this is related to this PR or not, but the view that renders the following page is missing a back to link at the top of the sidebar: https://dev-portal-git-kscollection-view-layout-hashicorp.vercel.app/vault/tutorials/secrets-management/static-secrets.

2022-04-13 20:02 UTC, ashleemboyer commented on src/views/collection-view/index.tsx
> +      <h2 id={layoutProps.headings[1].slug}>Tutorials</h2>
Do we _need_ to have this section be linkable? The `Sidecar` doesn't seem very useful in this view. The list of tutorials appears pretty close to the top of the page.

2022-04-13 20:19 UTC, zchsh commented on src/views/collection-view/index.tsx
> +      <h2 id={layoutProps.headings[1].slug}>Tutorials</h2>
☝️ +1, I think this is a great question for design. I raised it with Brayden, I think the intent here is that later there may be additional sections on the page? I think I remember it being mentioned that removing the `Sidecar` would create a strange whitespace balance as well.

Personally I'd be on board with removing it until we have more substance to put it in it; the whitespace balance drawback might also carry the benefit of better focus on the page (fewer elements).

2022-04-14 15:29 UTC, kendallstrautman commented on src/views/collection-view/index.tsx
> +      <h2 id={layoutProps.headings[1].slug}>Tutorials</h2>
Yeah let's check in with design about this. I think for this view there wouldn't be extra sections and I agree it doesn't seem _super_ useful. Maybe until we get clarity we just have it there?

2022-04-14 15:30 UTC, kendallstrautman commented on src/views/tutorial-view/server.ts
> +      product: { name: product.name, filename: product.slug },
That's fair, I just wanted the interface to be consistent. If its a blocker I can change it, but it seems pretty minor to me 🤷‍♀️

2022-04-14 15:38 UTC, kendallstrautman commented
@ashleemboyer the link you shared that shows a different sidebar layout (without the back to link)) is a tutorial view, so this PR wouldn't affect that. I think @zchsh is working on getting the tutorial sidebar up to date.

2022-04-14 15:45 UTC, kendallstrautman commented on src/views/collection-view/components/collection-view-sidebar.tsx
> +      title={`${product.name} Tutorials`}
Cool, I was referencing the template which could be out of date. Will update!

2022-04-14 16:17 UTC, ashleemboyer commented on src/pages/vault/tutorials/[collectionSlug].tsx
> +export default function VaultCollectionPage(
@kendallstrautman what I was suggesting here is that this (and the one for Waypoint):

```tsx
export default function VaultCollectionPage(
  props: CollectionPageProps
): React.ReactElement {
  return <CollectionView {...props} />
}
```

get replaced with this:

```tsx
export default CollectionView
```

Which is what a few product landing pages do with `ProductLandingView`:

- [Vault](https://github.com/hashicorp/dev-portal/blob/main/src/pages/vault/index.tsx#L16)
- [Waypoint](https://github.com/hashicorp/dev-portal/blob/main/src/pages/waypoint/index.tsx#L16)

2022-04-14 19:39 UTC, ashleemboyer approved these changes
✨

2022-04-14 21:15 UTC, merged