fix: adjust blur radius on filter input box shadow
hashicorp/dev-portal pull request #567
Opened 2022-06-07 22:57 UTC by kendallstrautman

## 🔗 Relevant links

- [Preview link](https://dev-portal-git-BRANCH_NAME-hashicorp.vercel.app/PATH_TO_VIEW) 🔎
- [Asana task](url) 🎟️

## 🗒️ What

## 🤷 Why

## 🛠️ How

## 📸 Design Screenshots

## 🧪 Testing

## 💭 Anything else?

2022-06-07 23:38 UTC, kendallstrautman commented on src/styles/sizing.css
> +  --input-height: 36px;
This seems to align with [the design spec](https://www.figma.com/file/VD7ahvXuXWJApeGnhbW4hv/DevDot?node-id=7502%3A73814) and also matches the search input height.

2022-06-07 23:38 UTC, kendallstrautman commented on src/components/sidebar/components/sidebar-filter-input/sidebar-filter-input.module.css
> +  box-shadow: var(--token-surface-inset-box-shadow);
lmk if there are concerns to moving this box shadow up to the wrapping div!

2022-06-08 00:20 UTC, BRKalow commented on src/components/sidebar/components/sidebar-filter-input/sidebar-filter-input.module.css
>    font-size: 14px;
Wanna change the font size here to 16px? This will prevent iOS from zooming in a bit when focusing the input.

2022-06-08 00:20 UTC, BRKalow commented
Looks good on my device!

2022-06-08 12:30 UTC, ashleemboyer commented
Reviewing now! 👀

2022-06-08 12:58 UTC, ashleemboyer requested changes
Did some searching on this `box-shadow` issue with `input`s on iOS and found something! Looks like we need to remove the default styling and then our custom styles should be applied as expected.

https://stackoverflow.com/a/23211766

Tested and confirmed with a CodeSandbox and my own iOS device: https://codesandbox.io/s/sharp-mcnulty-73v4g0?file=/styles.css

2022-06-08 19:15 UTC, kendallstrautman commented
@ashleemboyer awesome that worked. Thanks for finding that.

2022-06-08 20:21 UTC, ashleemboyer commented on src/components/sidebar/components/sidebar-filter-input/sidebar-filter-input.module.css
>    border: none;
We've been putting `composes` first inside of blocks like this and then placing CSS properties after that, can this be updated to do that here as well??

```suggestion
  composes: g-focus-ring-from-box-shadow from global;
  appearance: none;
  background-color: transparent;
  border: none;
  border-radius: 5px;
  box-shadow: var(--token-surface-inset-box-shadow);
```

2022-06-08 20:22 UTC, BRKalow approved these changes

2022-06-08 21:12 UTC, merged